insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (462, 'Food, Beverages & Tobacco', '{462}', 'Food, Beverages & Tobacco', 'Grocery');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (463, 'Dairy & Eggs', '{462,463}', 'Food, Beverages & Tobacco > Dairy & Eggs', 'Dairy & Eggs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (464, 'Milk', '{462,463,464}', 'Food, Beverages & Tobacco > Dairy & Eggs > Milk', 'Milk');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (466, 'Buttermilk', '{462,463,466}', 'Food, Beverages & Tobacco > Dairy & Eggs > Buttermilk', 'Buttermilk');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (468, 'Non-Dairy Milk', '{462,463,468}', 'Food, Beverages & Tobacco > Dairy & Eggs > Non-Dairy Milk', 'Non-Dairy Milk');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (470, 'Cheese', '{462,463,470}', 'Food, Beverages & Tobacco > Dairy & Eggs > Cheese', 'Cheese');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (472, 'Cream', '{462,463,472}', 'Food, Beverages & Tobacco > Dairy & Eggs > Cream', 'Cream');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (474, 'Butter & Margarine', '{462,463,474}', 'Food, Beverages & Tobacco > Dairy & Eggs > Butter & Margarine', 'Butter & Margarine');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (476, 'Yogurt', '{462,463,476}', 'Food, Beverages & Tobacco > Dairy & Eggs > Yogurt', 'Yogurt');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (478, 'Eggs', '{462,463,478}', 'Food, Beverages & Tobacco > Dairy & Eggs > Eggs', 'Eggs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (480, 'Meat & Seafood', '{462,480}', 'Food, Beverages & Tobacco > Meat & Seafood', 'Meat & Seafood');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (481, 'Fresh Meat', '{462,480,481}', 'Food, Beverages & Tobacco > Meat & Seafood > Fresh Meat', 'Fresh Meat');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (483, 'Poultry', '{462,480,483}', 'Food, Beverages & Tobacco > Meat & Seafood > Poultry', 'Poultry');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (485, 'Fish & Seafood', '{462,480,485}', 'Food, Beverages & Tobacco > Meat & Seafood > Fish & Seafood', 'Fish & Seafood');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (487, 'Deli', '{462,480,487}', 'Food, Beverages & Tobacco > Meat & Seafood > Deli', 'Deli');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (489, 'Bakery', '{462,489}', 'Food, Beverages & Tobacco > Bakery', 'Bakery');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (490, 'Bread', '{462,489,490}', 'Food, Beverages & Tobacco > Bakery > Bread', 'Bread');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (492, 'Cookies', '{462,489,492}', 'Food, Beverages & Tobacco > Bakery > Cookies', 'Cookies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (494, 'Cupcakes', '{462,489,494}', 'Food, Beverages & Tobacco > Bakery > Cupcakes', 'Cupcakes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (496, 'Muffins', '{462,489,496}', 'Food, Beverages & Tobacco > Bakery > Muffins', 'Muffins');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (498, 'Pastries', '{462,489,498}', 'Food, Beverages & Tobacco > Bakery > Pastries', 'Pastries');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (500, 'Tortillas & Wraps', '{462,489,500}', 'Food, Beverages & Tobacco > Bakery > Tortillas & Wraps', 'Tortillas & Wraps');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (502, 'Cooking & Baking Ingredients', '{462,502}', 'Food, Beverages & Tobacco > Cooking & Baking Ingredients', 'Cooking & Baking Ingredients');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (503, 'Baking Mixes', '{462,502,503}', 'Food, Beverages & Tobacco > Cooking & Baking Ingredients > Baking Mixes', 'Baking Mixes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (505, 'Baking Decorations', '{462,502,505}', 'Food, Beverages & Tobacco > Cooking & Baking Ingredients > Baking Decorations', 'Baking Decorations');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (507, 'Cooking Oils', '{462,502,507}', 'Food, Beverages & Tobacco > Cooking & Baking Ingredients > Cooking Oils', 'Cooking Oils');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (509, 'Produce', '{462,509}', 'Food, Beverages & Tobacco > Produce', 'Produce');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (510, 'Fruits', '{462,509,510}', 'Food, Beverages & Tobacco > Produce > Fruits', 'Fruits');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (512, 'Vegetables', '{462,509,512}', 'Food, Beverages & Tobacco > Produce > Vegetables', 'Vegetables');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (514, 'Fresh Herbs', '{462,509,514}', 'Food, Beverages & Tobacco > Produce > Fresh Herbs', 'Fresh Herbs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (516, 'Frozen Foods', '{462,516}', 'Food, Beverages & Tobacco > Frozen Foods', 'Frozen Foods');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (517, 'Frozen Meals', '{462,516,517}', 'Food, Beverages & Tobacco > Frozen Foods > Frozen Meals', 'Frozen Meals');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (519, 'Ice Cream & Novelties', '{462,516,519}', 'Food, Beverages & Tobacco > Frozen Foods > Ice Cream & Novelties', 'Ice Cream & Novelties');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (521, 'Frozen Vegetables & Fruits', '{462,516,521}', 'Food, Beverages & Tobacco > Frozen Foods > Frozen Vegetables & Fruits', 'Frozen Vegetables & Fruits');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (523, 'Canned & Jarred Goods', '{462,523}', 'Food, Beverages & Tobacco > Canned & Jarred Goods', 'Canned & Jarred Goods');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (524, 'Soups', '{462,523,524}', 'Food, Beverages & Tobacco > Canned & Jarred Goods > Soups', 'Soups');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (528, 'Pasta Sauces', '{462,523,528}', 'Food, Beverages & Tobacco > Canned & Jarred Goods > Pasta Sauces', 'Pasta Sauces');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (530, 'Pasta, Rice & Grains', '{462,530}', 'Food, Beverages & Tobacco > Pasta, Rice & Grains', 'Pasta, Rice & Grains');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (532, 'Condiments & Sauces', '{462,532}', 'Food, Beverages & Tobacco > Condiments & Sauces', 'Condiments & Sauces');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (534, 'Curry Sauce', '{462,532,534}', 'Food, Beverages & Tobacco > Condiments & Sauces > Curry Sauce', 'Curry Sauce');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (536, 'Honey', '{462,532,536}', 'Food, Beverages & Tobacco > Condiments & Sauces > Honey', 'Honey');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (538, 'Hot Sauce', '{462,532,538}', 'Food, Beverages & Tobacco > Condiments & Sauces > Hot Sauce', 'Hot Sauce');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (540, 'Ketchup', '{462,532,540}', 'Food, Beverages & Tobacco > Condiments & Sauces > Ketchup', 'Ketchup');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (542, 'Mayonnaise', '{462,532,542}', 'Food, Beverages & Tobacco > Condiments & Sauces > Mayonnaise', 'Mayonnaise');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (544, 'Olives', '{462,532,544}', 'Food, Beverages & Tobacco > Condiments & Sauces > Olives', 'Olives');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (546, 'Capers', '{462,532,546}', 'Food, Beverages & Tobacco > Condiments & Sauces > Capers', 'Capers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (548, 'Marinades & Grilling Sauces', '{462,532,548}', 'Food, Beverages & Tobacco > Condiments & Sauces > Marinades & Grilling Sauces', 'Marinades & Grilling Sauces');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (550, 'Relish & Chutney', '{462,532,550}', 'Food, Beverages & Tobacco > Condiments & Sauces > Relish & Chutney', 'Relish & Chutney');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (552, 'Salad Dressing', '{462,532,552}', 'Food, Beverages & Tobacco > Condiments & Sauces > Salad Dressing', 'Salad Dressing');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (554, 'Syrup', '{462,532,554}', 'Food, Beverages & Tobacco > Condiments & Sauces > Syrup', 'Syrup');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (556, 'Breakfast Foods', '{462,556}', 'Food, Beverages & Tobacco > Breakfast Foods', 'Breakfast Foods');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (557, 'Cereal', '{462,556,557}', 'Food, Beverages & Tobacco > Breakfast Foods > Cereal', 'Cereal');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (559, 'Pancake Mix & Syrup', '{462,556,559}', 'Food, Beverages & Tobacco > Breakfast Foods > Pancake Mix & Syrup', 'Pancake Mix & Syrup');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (561, 'Snacks', '{462,561}', 'Food, Beverages & Tobacco > Snacks', 'Snacks');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (562, 'Chips', '{462,561,562}', 'Food, Beverages & Tobacco > Snacks > Chips', 'Chips');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (564, 'Crackers', '{462,561,564}', 'Food, Beverages & Tobacco > Snacks > Crackers', 'Crackers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (566, 'Nuts & Seeds', '{462,561,566}', 'Food, Beverages & Tobacco > Snacks > Nuts & Seeds', 'Nuts & Seeds');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (569, 'Granola Bars', '{462,561,569}', 'Food, Beverages & Tobacco > Snacks > Granola Bars', 'Granola Bars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (571, 'Baby Food', '{462,571}', 'Food, Beverages & Tobacco > Baby Food', 'Baby Food');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (573, 'Beverages', '{462,573}', 'Food, Beverages & Tobacco > Beverages', 'Beverages');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (574, 'Water', '{462,573,574}', 'Food, Beverages & Tobacco > Beverages > Water', 'Water');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (576, 'Spring Water', '{462,573,574,576}', 'Food, Beverages & Tobacco > Beverages > Water > Spring Water', 'Spring Water');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (578, 'Carbonated Water', '{462,573,574,578}', 'Food, Beverages & Tobacco > Beverages > Water > Carbonated Water', 'Carbonated Water');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (580, 'Juice', '{462,573,580}', 'Food, Beverages & Tobacco > Beverages > Juice', 'Juice');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (582, 'Milk & Plant-Based Alternatives', '{462,573,582}', 'Food, Beverages & Tobacco > Beverages > Milk & Plant-Based Alternatives', 'Milk & Plant-Based Alternatives');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (584, 'Sodas & Soft Drinks', '{462,573,584}', 'Food, Beverages & Tobacco > Beverages > Sodas & Soft Drinks', 'Sodas & Soft Drinks');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (586, 'Coffee, Tea, & Infusions', '{462,573,586}', 'Food, Beverages & Tobacco > Beverages > Coffee, Tea, & Infusions', 'Coffee, Tea, & Infusions');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (588, 'Sports & Energy Drinks', '{462,573,588}', 'Food, Beverages & Tobacco > Beverages > Sports & Energy Drinks', 'Sports & Energy Drinks');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (590, 'Powdered Beverage Mixes', '{462,573,590}', 'Food, Beverages & Tobacco > Beverages > Powdered Beverage Mixes', 'Powdered Beverage Mixes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (592, 'Alcoholic Beverages', '{462,573,592}', 'Food, Beverages & Tobacco > Beverages > Alcoholic Beverages', 'Alcoholic Beverages');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (593, 'Beer', '{462,573,592,593}', 'Food, Beverages & Tobacco > Beverages > Alcoholic Beverages > Beer', 'Beer');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (595, 'Wine', '{462,573,592,595}', 'Food, Beverages & Tobacco > Beverages > Alcoholic Beverages > Wine', 'Wine');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (597, 'Spirits', '{462,573,592,597}', 'Food, Beverages & Tobacco > Beverages > Alcoholic Beverages > Spirits', 'Spirits');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (599, 'Tobacco', '{462,599}', 'Food, Beverages & Tobacco > Tobacco', 'Tobacco');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (600, 'Cigarettes', '{462,599,600}', 'Food, Beverages & Tobacco > Tobacco > Cigarettes', 'Cigarettes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (602, 'Cigars', '{462,599,602}', 'Food, Beverages & Tobacco > Tobacco > Cigars', 'Cigars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (604, 'Smokeless Tobacco', '{462,599,604}', 'Food, Beverages & Tobacco > Tobacco > Smokeless Tobacco', 'Smokeless Tobacco');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (606, 'Vapes & Accessories', '{462,599,606}', 'Food, Beverages & Tobacco > Tobacco > Vapes & Accessories', 'Vapes & Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (609, 'Dips & Spreads', '{462,609}', 'Food, Beverages & Tobacco > Dips & Spreads', 'Dips & Spreads');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (610, 'Jams & Jellies', '{462,609,610}', 'Food, Beverages & Tobacco > Dips & Spreads > Jams & Jellies', 'Jams & Jellies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (612, 'Nut Butters', '{462,609,612}', 'Food, Beverages & Tobacco > Dips & Spreads > Nut Butters', 'Nut Butters');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (614, 'Salsa', '{462,609,614}', 'Food, Beverages & Tobacco > Dips & Spreads > Salsa', 'Salsa');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (616, 'Frozen Desserts & Novelties', '{462,616}', 'Food, Beverages & Tobacco > Frozen Desserts & Novelties', 'Frozen Desserts & Novelties');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (617, 'Ice Cream', '{462,616,617}', 'Food, Beverages & Tobacco > Frozen Desserts & Novelties > Ice Cream', 'Ice Cream');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (619, 'Frozen Yogurt', '{462,616,619}', 'Food, Beverages & Tobacco > Frozen Desserts & Novelties > Frozen Yogurt', 'Frozen Yogurt');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (621, 'Fruits & Vegetables', '{462,621}', 'Food, Beverages & Tobacco > Fruits & Vegetables', 'Fruits & Vegetables');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (622, 'Canned & Jarred Vegetables', '{462,621,622}', 'Food, Beverages & Tobacco > Fruits & Vegetables > Canned & Jarred Vegetables', 'Canned & Jarred Vegetables');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (624, 'Dried Fruits', '{462,621,624}', 'Food, Beverages & Tobacco > Fruits & Vegetables > Dried Fruits', 'Dried Fruits');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (626, 'Pickled Fruits & Vegetables', '{462,621,626}', 'Food, Beverages & Tobacco > Fruits & Vegetables > Pickled Fruits & Vegetables', 'Pickled Fruits & Vegetables');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (628, 'Fresh & Frozen Vegetables', '{462,621,628}', 'Food, Beverages & Tobacco > Fruits & Vegetables > Fresh & Frozen Vegetables', 'Fresh & Frozen Vegetables');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (629, 'Tomatoes', '{462,621,628,629}', 'Food, Beverages & Tobacco > Fruits & Vegetables > Fresh & Frozen Vegetables > Tomatoes', 'Tomatoes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (631, 'Grains, Rice & Cereal', '{462,631}', 'Food, Beverages & Tobacco > Grains, Rice & Cereal', 'Grains, Rice & Cereal');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (632, 'Cereal & Granola', '{462,631,632}', 'Food, Beverages & Tobacco > Grains, Rice & Cereal > Cereal & Granola', 'Cereal & Granola');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (635, 'Pasta & Noodles', '{462,635}', 'Food, Beverages & Tobacco > Pasta & Noodles', 'Pasta & Noodles');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (637, 'Seasonings & Spices', '{462,637}', 'Food, Beverages & Tobacco > Seasonings & Spices', 'Seasonings & Spices');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (638, 'Herbs & Spices', '{462,637,638}', 'Food, Beverages & Tobacco > Seasonings & Spices > Herbs & Spices', 'Herbs & Spices');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (640, 'Pepper', '{462,637,640}', 'Food, Beverages & Tobacco > Seasonings & Spices > Pepper', 'Pepper');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (642, 'Snack Foods', '{462,642}', 'Food, Beverages & Tobacco > Snack Foods', 'Snack Foods');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (643, 'Cereal & Granola Bars', '{462,642,643}', 'Food, Beverages & Tobacco > Snack Foods > Cereal & Granola Bars', 'Cereal & Granola Bars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (645, 'Cereal Bars', '{462,642,643,645}', 'Food, Beverages & Tobacco > Snack Foods > Cereal & Granola Bars > Cereal Bars', 'Cereal Bars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (647, 'Cheese Puffs', '{462,642,647}', 'Food, Beverages & Tobacco > Snack Foods > Cheese Puffs', 'Cheese Puffs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (649, 'Popcorn', '{462,642,649}', 'Food, Beverages & Tobacco > Snack Foods > Popcorn', 'Popcorn');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (651, 'Candy & Chocolate', '{462,651}', 'Food, Beverages & Tobacco > Candy & Chocolate', 'Candy & Chocolate');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (653, 'Soups & Broths', '{462,653}', 'Food, Beverages & Tobacco > Soups & Broths', 'Soups & Broths');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (655, 'Health & Personal Care', '{655}', 'Health & Personal Care', 'Health & Personal Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (656, 'Over-the-Counter Medication', '{655,656}', 'Health & Personal Care > Over-the-Counter Medication', 'Over-the-Counter Medication');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (658, 'First Aid', '{655,658}', 'Health & Personal Care > First Aid', 'First Aid');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (660, 'Vitamins & Supplements', '{655,660}', 'Health & Personal Care > Vitamins & Supplements', 'Vitamins & Supplements');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (662, 'Skin Care', '{655,662}', 'Health & Personal Care > Skin Care', 'Skin Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (664, 'Hair Care', '{655,664}', 'Health & Personal Care > Hair Care', 'Hair Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (666, 'Oral Care', '{655,666}', 'Health & Personal Care > Oral Care', 'Oral Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (668, 'Feminine Care', '{655,668}', 'Health & Personal Care > Feminine Care', 'Feminine Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (670, 'Deodorants', '{655,670}', 'Health & Personal Care > Deodorants', 'Deodorants');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (672, 'Hygiene Products', '{655,672}', 'Health & Personal Care > Hygiene Products', 'Hygiene Products');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (674, 'Liquid Hand Soap', '{655,672,674}', 'Health & Personal Care > Hygiene Products > Liquid Hand Soap', 'Liquid Hand Soap');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (676, 'Bar Soap', '{655,672,676}', 'Health & Personal Care > Hygiene Products > Bar Soap', 'Bar Soap');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (678, 'Body Wash', '{655,672,678}', 'Health & Personal Care > Hygiene Products > Body Wash', 'Body Wash');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (680, 'Bath Additives', '{655,672,680}', 'Health & Personal Care > Hygiene Products > Bath Additives', 'Bath Additives');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (682, 'Eye & Ear Care', '{655,682}', 'Health & Personal Care > Eye & Ear Care', 'Eye & Ear Care');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (685, 'Fitness & Nutrition', '{655,685}', 'Health & Personal Care > Fitness & Nutrition', 'Fitness & Nutrition');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (686, 'Nutrition Drinks & Shakes', '{655,685,686}', 'Health & Personal Care > Fitness & Nutrition > Nutrition Drinks & Shakes', 'Nutrition Drinks & Shakes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (689, 'Medicine & Drugs', '{655,689}', 'Health & Personal Care > Medicine & Drugs', 'Medicine & Drugs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (691, 'Cosmetics', '{655,691}', 'Health & Personal Care > Cosmetics', 'Cosmetics');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (692, 'Bath & Body', '{655,691,692}', 'Health & Personal Care > Cosmetics > Bath & Body', 'Bath & Body');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (694, 'Body Powder', '{655,662,694}', 'Health & Personal Care > Cosmetics > Skin Care > Body Powder', 'Body Powder');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (696, 'Facial Cleansers', '{655,662,696}', 'Health & Personal Care > Cosmetics > Skin Care > Facial Cleansers', 'Facial Cleansers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (698, 'Lotion & Moisturizer', '{655,662,698}', 'Health & Personal Care > Cosmetics > Skin Care > Lotion & Moisturizer', 'Lotion & Moisturizer');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (700, 'Deodorant & Anti-Perspirant', '{655,700}', 'Health & Personal Care > Deodorant & Anti-Perspirant', 'Deodorant & Anti-Perspirant');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (702, 'Shampoo & Conditioner', '{655,664,702}', 'Health & Personal Care > Hair Care > Shampoo & Conditioner', 'Shampoo & Conditioner');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (704, 'Shaving Cream', '{655,664,704}', 'Health & Personal Care > Hair Care > Shaving Cream', 'Shaving Cream');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (706, 'Dental Floss', '{655,666,706}', 'Health & Personal Care > Oral Care > Dental Floss', 'Dental Floss');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (708, 'Toothpaste', '{655,666,708}', 'Health & Personal Care > Oral Care > Toothpaste', 'Toothpaste');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (710, 'Household Supplies', '{710}', 'Household Supplies', 'Household Supplies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (711, 'Cleaning Supplies', '{710,711}', 'Household Supplies > Cleaning Supplies', 'Cleaning Supplies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (713, 'All-Purpose Cleaners', '{710,711,713}', 'Household Supplies > Cleaning Supplies > All-Purpose Cleaners', 'All-Purpose Cleaners');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (715, 'Floor Cleaners', '{710,711,715}', 'Household Supplies > Cleaning Supplies > Floor Cleaners', 'Floor Cleaners');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (717, 'Disinfectants', '{710,711,717}', 'Household Supplies > Cleaning Supplies > Disinfectants', 'Disinfectants');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (719, 'Sponges & Scouring Pads', '{710,711,719}', 'Household Supplies > Cleaning Supplies > Sponges & Scouring Pads', 'Sponges & Scouring Pads');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (721, 'Laundry Detergents & Softeners', '{710,721}', 'Household Supplies > Laundry Detergents & Softeners', 'Laundry Detergents & Softeners');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (723, 'Dish Detergent & Soap', '{710,723}', 'Household Supplies > Dish Detergent & Soap', 'Dish Detergent & Soap');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (725, 'Paper Products', '{710,725}', 'Household Supplies > Paper Products', 'Paper Products');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (726, 'Toilet Paper', '{710,725,726}', 'Household Supplies > Paper Products > Toilet Paper', 'Toilet Paper');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (728, 'Paper Towels', '{710,725,728}', 'Household Supplies > Paper Products > Paper Towels', 'Paper Towels');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (730, 'Facial Tissues', '{710,725,730}', 'Household Supplies > Paper Products > Facial Tissues', 'Facial Tissues');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (732, 'Trash Bags', '{710,732}', 'Household Supplies > Trash Bags', 'Trash Bags');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (734, 'Dishwashing Products', '{710,734}', 'Household Supplies > Dishwashing Products', 'Dishwashing Products');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (736, 'Air Fresheners', '{710,736}', 'Household Supplies > Air Fresheners', 'Air Fresheners');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (738, 'Fragrance Oil', '{710,738}', 'Household Supplies > Fragrance Oil', 'Fragrance Oil');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (740, 'Bathroom Accessories', '{710,740}', 'Household Supplies > Bathroom Accessories', 'Bathroom Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (742, 'Laundry Supplies', '{710,742}', 'Household Supplies > Laundry Supplies', 'Laundry Supplies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (743, 'Fabric Stain Removers', '{710,742,743}', 'Household Supplies > Laundry Supplies > Fabric Stain Removers', 'Fabric Stain Removers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (745, 'Bleach', '{710,742,745}', 'Household Supplies > Laundry Supplies > Bleach', 'Bleach');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (747, 'Baby & Childcare', '{747}', 'Baby & Childcare', 'Baby & Childcare');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (748, 'Baby Diapers', '{747,748}', 'Baby & Childcare > Baby Diapers', 'Baby Diapers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (750, 'Baby Wipes', '{747,750}', 'Baby & Childcare > Baby Wipes', 'Baby Wipes');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (752, 'Baby Formula', '{747,752}', 'Baby & Childcare > Baby Formula', 'Baby Formula');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (755, 'Baby Toiletries', '{747,755}', 'Baby & Childcare > Baby Toiletries', 'Baby Toiletries');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (757, 'Bottles & Feeding Accessories', '{747,757}', 'Baby & Childcare > Bottles & Feeding Accessories', 'Bottles & Feeding Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (759, 'Pets', '{759}', 'Pets', 'Pets');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (760, 'Dog Food', '{759,760}', 'Pets > Dog Food', 'Dog Food');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (762, 'Cat Food', '{759,762}', 'Pets > Cat Food', 'Cat Food');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (764, 'Treats', '{759,764}', 'Pets > Treats', 'Treats');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (766, 'Litter & Training Pads', '{759,766}', 'Pets > Litter & Training Pads', 'Litter & Training Pads');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (768, 'Toys & Accessories', '{759,768}', 'Pets > Toys & Accessories', 'Toys & Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (770, 'Tools & Home Improvement', '{770}', 'Tools & Home Improvement', 'Tools & Home Improvement');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (771, 'Hand Tools', '{770,771}', 'Tools & Home Improvement > Hand Tools', 'Hand Tools');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (773, 'Power Tools', '{770,773}', 'Tools & Home Improvement > Power Tools', 'Power Tools');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (775, 'Hardware', '{770,775}', 'Tools & Home Improvement > Hardware', 'Hardware');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (777, 'Light Bulbs', '{770,777}', 'Tools & Home Improvement > Light Bulbs', 'Light Bulbs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (779, 'Batteries', '{770,779}', 'Tools & Home Improvement > Batteries', 'Batteries');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (781, 'Electrical Supplies', '{770,781}', 'Tools & Home Improvement > Electrical Supplies', 'Electrical Supplies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (783, 'Apparel & Accessories', '{783}', 'Apparel & Accessories', 'Apparel & Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (784, 'Clothing', '{783,784}', 'Apparel & Accessories > Clothing', 'Clothing');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (785, 'Underwear & Socks', '{783,784,785}', 'Apparel & Accessories > Clothing > Underwear & Socks', 'Underwear & Socks');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (787, 'Arts & Entertainment', '{787}', 'Arts & Entertainment', 'Arts & Entertainment');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (788, 'Hobbies & Creative Arts', '{787,788}', 'Arts & Entertainment > Hobbies & Creative Arts', 'Hobbies & Creative Arts');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (789, 'Arts & Crafts', '{787,788,789}', 'Arts & Entertainment > Hobbies & Creative Arts > Arts & Crafts', 'Arts & Crafts');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (791, 'Hardware Accessories', '{770,775,791}', 'Hardware > Hardware Accessories', 'Hardware Accessories');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (792, 'Hardware Fasteners', '{770,775,791,792}', 'Hardware > Hardware Accessories > Hardware Fasteners', 'Hardware Fasteners');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (794, 'Home & Garden', '{794}', 'Home & Garden', 'Home & Garden');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (795, 'Plants', '{794,795}', 'Home & Garden > Plants', 'Plants');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (797, 'Media', '{797}', 'Media', 'Media');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (798, 'Music & Sound Recordings', '{797,798}', 'Media > Music & Sound Recordings', 'Music & Sound Recordings');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (799, 'Music CDs', '{797,798,799}', 'Media > Music & Sound Recordings > Music CDs', 'Music CDs');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (801, 'Sporting Goods', '{801}', 'Sporting Goods', 'Sporting Goods');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (802, 'Outdoor Recreation', '{801,802}', 'Sporting Goods > Outdoor Recreation', 'Outdoor Recreation');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (803, 'Hydration Systems', '{801,802,803}', 'Sporting Goods > Outdoor Recreation > Hydration Systems', 'Hydration Systems');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (805, 'Kitchen & Dining', '{794,805}', 'Home & Garden > Kitchen & Dining', 'Kitchen & Dining');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (806, 'Cookware & Bakeware', '{794,805,806}', 'Home & Garden > Kitchen & Dining > Cookware & Bakeware', 'Cookware & Bakeware');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (807, 'Bakeware', '{794,805,806,807}', 'Home & Garden > Kitchen & Dining > Cookware & Bakeware > Bakeware', 'Bakeware');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (809, 'Food & Beverage Carriers', '{794,805,809}', 'Home & Garden > Kitchen & Dining > Food & Beverage Carriers', 'Food & Beverage Carriers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (811, 'Food Storage', '{794,805,811}', 'Home & Garden > Kitchen & Dining > Food Storage', 'Food Storage');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (812, 'Cookie Jars', '{794,805,811,812}', 'Home & Garden > Kitchen & Dining > Food Storage > Cookie Jars', 'Cookie Jars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (814, 'Honey Jars', '{794,805,811,814}', 'Home & Garden > Kitchen & Dining > Food Storage > Honey Jars', 'Honey Jars');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (816, 'Kitchen Tools & Utensils', '{794,805,816}', 'Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils', 'Kitchen Tools & Utensils');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (817, 'Oil & Vinegar Dispensers', '{794,805,816,817}', 'Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils > Oil & Vinegar Dispensers', 'Oil & Vinegar Dispensers');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (819, 'Waste Containment', '{710,819}', 'Home & Garden > Household Supplies > Waste Containment', 'Waste Containment');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (820, 'Trash Cans & Wastebaskets', '{710,819,820}', 'Home & Garden > Household Supplies > Waste Containment > Trash Cans & Wastebaskets', 'Trash Cans & Wastebaskets');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (822, 'Lighting', '{794,822}', 'Home & Garden > Lighting', 'Lighting');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (823, 'Lamps', '{794,822,823}', 'Home & Garden > Lighting > Lamps', 'Lamps');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (825, 'Office Supplies', '{825}', 'Office Supplies', 'Office Supplies');
insert into "category" ("id", "name", "path", "expanded_pathname", "alias") values (826, 'Pen Ink & Refills', '{825,826}', 'Office Supplies > Pen Ink & Refills', 'Pen Ink & Refills');
